/** Pixaroid PDF Engine v4.1 - repaired shared browser engine. */
class PDFEngine {
  constructor(){this.PDFLib=null;this.PDFJS=null;this.loadedDocs=new Map();this.worker=null;this.jobCounter=0;this.pendingJobs=new Map();this.workerManager=null;}
  async init(){if(!this.PDFLib)await this.loadPdfLib();if(!this.PDFJS)await this.loadPdfJs();return this;}
  async loadPdfLib(){return new Promise((resolve,reject)=>{if(window.PDFLib){this.PDFLib=window.PDFLib;resolve(this.PDFLib);return;}const script=document.createElement('script');script.src='https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js';script.onload=()=>{this.PDFLib=window.PDFLib;resolve(this.PDFLib);};script.onerror=reject;document.head.appendChild(script);});}
  async loadPdfJs(){return new Promise((resolve,reject)=>{if(window.pdfjsLib){this.PDFJS=window.pdfjsLib;this.PDFJS.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';resolve(this.PDFJS);return;}const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';script.onload=()=>{window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';this.PDFJS=window.pdfjsLib;resolve(this.PDFJS);};script.onerror=reject;document.head.appendChild(script);});}
  async merge(files,options={}){await this.init();const {PDFDocument}=this.PDFLib,doc=await PDFDocument.create();for(let i=0;i<files.length;i++){const src=await PDFDocument.load(await this.readFileAsArrayBuffer(files[i]));(await doc.copyPages(src,src.getPageIndices())).forEach(p=>doc.addPage(p));options.onProgress?.(Math.round((i+1)/files.length*100));}return new Blob([await doc.save()],{type:'application/pdf'});}
  async split(file,options={}){await this.init();const {PDFDocument}=this.PDFLib,src=await PDFDocument.load(await this.readFileAsArrayBuffer(file)),indices=this.parsePageRange(options.range,src.getPageCount());if(indices.length===1){const d=await PDFDocument.create();d.addPage((await d.copyPages(src,[indices[0]]))[0]);return new Blob([await d.save()],{type:'application/pdf'});}const out=[];for(let i=0;i<indices.length;i++){const d=await PDFDocument.create();d.addPage((await d.copyPages(src,[indices[i]]))[0]);out.push(new Blob([await d.save()],{type:'application/pdf'}));options.onProgress?.(Math.round((i+1)/indices.length*100));}return out;}
  async compress(file,options={}){await this.init();const {PDFDocument}=this.PDFLib,pdf=await this.PDFJS.getDocument({data:await this.readFileAsArrayBuffer(file)}).promise,level=options.level||'medium',dpi={low:150,medium:120,high:96,extreme:72}[level]||120,scale=dpi/72,quality=dpi<=96?.6:dpi<=120?.75:.88,out=await PDFDocument.create();for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),vp=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(vp.width));canvas.height=Math.max(1,Math.round(vp.height));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:vp}).promise;const blob=await this.canvasToBlob(canvas,'image/jpeg',quality),img=await out.embedJpg(await blob.arrayBuffer()),orig=page.getViewport({scale:1}),p=out.addPage([orig.width,orig.height]);p.drawImage(img,{x:0,y:0,width:orig.width,height:orig.height});options.onProgress?.(Math.round(i/pdf.numPages*100));}return new Blob([await out.save()],{type:'application/pdf'});}
  async rotate(file,options={}){await this.init();const {PDFDocument,degrees}=this.PDFLib,doc=await PDFDocument.load(await this.readFileAsArrayBuffer(file)),pages=doc.getPages(),angleMap={'90':90,'180':180,'270':270,'-90':270,'-180':180,'-270':90},angle=angleMap[String(options.angle)]||90,indices=options.pages?this.parsePageRange(options.pages,pages.length):pages.map((_,i)=>i),set=new Set(indices);pages.forEach((p,i)=>{if(set.has(i))p.setRotation(degrees((p.getRotation().angle+angle+360)%360));});return new Blob([await doc.save()],{type:'application/pdf'});}
  async watermark(file,options={}){await this.init();const {PDFDocument,rgb,degrees,StandardFonts}=this.PDFLib,doc=await PDFDocument.load(await this.readFileAsArrayBuffer(file)),pages=doc.getPages(),font=await doc.embedFont(StandardFonts.HelveticaBold),text=options.text||'CONFIDENTIAL',opacity=Math.max(0,Math.min(1,(parseFloat(options.opacity)??30)/100)),rotation=parseFloat(options.rotation)??-45,hex=(options.color||'#808080').replace('#','').padEnd(6,'8'),color=rgb(parseInt(hex.slice(0,2),16)/255,parseInt(hex.slice(2,4),16)/255,parseInt(hex.slice(4,6),16)/255),indices=options.pages?this.parsePageRange(options.pages,pages.length):pages.map((_,i)=>i),set=new Set(indices);pages.forEach((p,i)=>{if(set.has(i)){const {width,height}=p.getSize(),size=Math.max(24,Math.min(72,width*.07));p.drawText(text,{x:(width-font.widthOfTextAtSize(text,size))/2,y:height/2,size,font,color,opacity,rotate:degrees(rotation)});}options.onProgress?.(Math.round((i+1)/pages.length*100));});return new Blob([await doc.save()],{type:'application/pdf'});}
  async imagesToPdf(images,options={}){await this.init();const {PDFDocument}=this.PDFLib,doc=await PDFDocument.create(),sizes={A4:[595.28,841.89],Letter:[612,792],A3:[841.89,1190.55],Legal:[612,1008]},size=sizes[options.pageSize||'A4']||sizes.A4,margin=Math.max(0,Number(options.margin)||10),quality=Math.max(.01,Math.min(1,(Number(options.quality)||90)/100));let [pw,ph]=size;if(options.orientation==='landscape')[pw,ph]=[ph,pw];for(let i=0;i<images.length;i++){const bitmap=await createImageBitmap(images[i]);let canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0);bitmap.close();const jpeg=await this.canvasToBlob(canvas,'image/jpeg',quality),img=await doc.embedJpg(await jpeg.arrayBuffer()),page=doc.addPage([pw,ph]),aw=Math.max(1,pw-margin*2),ah=Math.max(1,ph-margin*2),scale=Math.min(aw/img.width,ah/img.height),w=img.width*scale,h=img.height*scale;page.drawImage(img,{x:(pw-w)/2,y:(ph-h)/2,width:w,height:h});options.onProgress?.(Math.round((i+1)/images.length*100));}return new Blob([await doc.save()],{type:'application/pdf'});}
  async pdfToImages(file,options={}){await this.init();const pdf=await this.PDFJS.getDocument({data:await this.readFileAsArrayBuffer(file)}).promise,dpi={72:72,150:150,300:300}[String(options.dpi)]||150,scale=dpi/72,format=options.format||'jpeg',quality=Math.max(.01,Math.min(1,(parseInt(options.quality)||90)/100)),out=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),vp=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(vp.width));canvas.height=Math.max(1,Math.round(vp.height));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:vp}).promise;out.push(await this.canvasToBlob(canvas,format==='png'?'image/png':'image/jpeg',quality));options.onProgress?.(Math.round(i/pdf.numPages*100));}return out;}
  async pdfToWord(file,options={}){await this.init();const pdf=await this.PDFJS.getDocument({data:await this.readFileAsArrayBuffer(file)}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),tc=await page.getTextContent(),pt=tc.items.map(x=>x.str).join(' ');if(pt.trim())text+=`--- Page ${i} ---\n${pt}\n\n`;options.onProgress?.(Math.round(i/pdf.numPages*100));}return new Blob([`{\\rtf1\\ansi\\deff0\n{\\fonttbl{\\f0 Arial;}}\n\\f0\\fs24 ${this.escapeRtf(text)}}`],{type:'application/rtf'});}
  parsePageRange(rangeStr,total){if(!rangeStr||!String(rangeStr).trim())return Array.from({length:total},(_,i)=>i);const indices=[];String(rangeStr).split(',').forEach(part=>{part=part.trim();const dash=part.indexOf('-');if(dash>0){let a=parseInt(part)-1,b=parseInt(part.slice(dash+1))-1;if(Number.isFinite(a)&&Number.isFinite(b)){for(let i=Math.max(0,a);i<=Math.min(b,total-1);i++)indices.push(i);}}else{const n=parseInt(part)-1;if(n>=0&&n<total)indices.push(n);}});return indices.length?[...new Set(indices)]:Array.from({length:total},(_,i)=>i);}
  readFileAsArrayBuffer(file){return file.arrayBuffer?file.arrayBuffer():new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsArrayBuffer(file);});}
  canvasToBlob(canvas,type,quality){return new Promise((resolve,reject)=>{canvas.toBlob(b=>b?resolve(b):reject(new Error('Canvas export failed')),type,quality);});}
  dataUrlToBlob(dataUrl){const m=String(dataUrl).match(/^data:(.*?);base64,(.*)$/);if(!m)throw new Error('Invalid data URL');const b=atob(m[2]),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new Blob([u],{type:m[1]});}
  escapeRtf(text){return String(text).replace(/\\/g,'\\\\').replace(/{/g,'\\{').replace(/}/g,'\\}').replace(/\n/g,'\\par\n');}
}
if(typeof window!=='undefined')window.PDFEngine=PDFEngine;
